name: Python CI

on:
    workflow_dispatch:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout codigo
        uses: actions/checkout@v3

      - name: configurando Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - name: instalando dependencias
        run: |
            python -m pip install --upgrade pip
            pip install -r src/requirements.txt

      - name: executar testes
        run: pytest src/testes/ --junitxml=report.xml

      - name: armazenando relatorio de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml